### ISSUE TITLE
(optional) Use imgix-core-js

### ISSUE THREAD

**Issue by kellysutton** [bustlelabs/ember-imgix-helper#1]
imgix has a JavaScript library that can be helpful for building URLs: https://github.com/imgix/imgix-core-js

For ember, we've also got a shim: https://github.com/imgix/ember-cli-imgix-core-js-shim

Probably not useful for how simple this is at the moment, but it might help! Feel free to close this issue.

**Comment by gpoitch** [comment]
Thanks, this is just supposed to be really basic, not the full-blown lib.

**Comment by kellysutton** [comment]
:+1:
